spring:
  ai:
    # OpenAI Configuration
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4}
          max-tokens: 4000
          temperature: 0.7
    
    # Azure OpenAI Configuration
    azure:
      openai:
        endpoint: ${AZURE_OPENAI_ENDPOINT:https://your-resource.openai.azure.com}
        api-key: ${AZURE_OPENAI_API_KEY:your-azure-api-key-here}
        chat:
          options:
            deployment-name: ${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-4}
            max-tokens: 4000
            temperature: 0.7
    
    # MCP Server Configuration
    mcp:
      server:
        enabled: true
        name: "Campaign Journey MCP Server"
        version: "1.0.0"
        description: "MCP Server for marketing campaign journey management using Spring AI"
      
      # MCP Client Configuration
      client:
        enabled: true
        name: "campaign-journey-mcp-client"
        version: "1.0.0"
        type: SYNC  # or ASYNC for reactive applications
        request-timeout: 30s
        initialized: true
        root-change-notification: true
        toolcallback:
          enabled: true
        
        # SSE Transport Configuration
        sse:
          connections:
            local-server:
              url: http://localhost:8080
              sse-endpoint: /sse
        
        # Stdio Transport Configuration (optional)
        stdio:
          root-change-notification: false
          connections:
            local-server:
              command: java
              args:
                - -jar
                - mcp-server.jar
              env:
                DEBUG: "true"

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.springframework.ai: DEBUG
    com.example.mcp: DEBUG
    org.springframework.ai.mcp: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mcp
  endpoint:
    health:
      show-details: always 