spring:
  ai:
    # OpenAI Configuration
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4}
          max-tokens: 4000
          temperature: 0.7
    
    # Azure OpenAI Configuration
    azure:
      openai:
        endpoint: ${AZURE_OPENAI_ENDPOINT:https://your-resource.openai.azure.com}
        api-key: ${AZURE_OPENAI_API_KEY:your-azure-api-key-here}
        chat:
          options:
            deployment-name: ${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-4}
            max-tokens: 4000
            temperature: 0.7
    
    # MCP Server Configuration - Spring AI 1.0.1 format
    mcp:
      server:
        enabled: true
        name: "Campaign Journey MCP Server"
        version: "1.0.0"
        description: "MCP Server for marketing campaign journey management using Spring AI"
        transport: stdio
        # Stdio transport configuration
        stdio:
          enabled: true
          root-change-notification: false
      # MCP Client Configuration
      client:
        enabled: true
        marketing:
          service:
            path: "/path/to/marketing/service"
    
    # Disable tool calling to avoid OAuth2 dependency issues
    model:
      tool:
        enabled: false
  
  # Disable Spring Security for MCP stdio server
  security:
    enabled: false
    basic:
      enabled: false
    user:
      name: ""
      password: ""

# Server Configuration - Minimal for stdio transport
server:
  port: 8088

# Logging Configuration
logging:
  level:
    org.springframework.ai: DEBUG
    com.example.mcp: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.security: OFF
    org.springframework.boot.actuate: OFF

# Actuator Configuration - Disabled security
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 1
    display-request-duration: true
  packages-to-scan: com.example.mcp.controller
  paths-to-match: /api/**